[package]
name = "fiis"
version = "0.0.1"
edition = "2024"

[dependencies]
clap = {version = "4.5.53", features = ["derive"]}
colored = "3.0.0"
hound = "3.5.1"
indicatif = "0.18.3"
ringbuffer = "0.16.0"
